name: Jammy

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ master ]

  schedule:
    - cron:  '0 0 * * *' # at the end of every day

  workflow_dispatch:

jobs:

  cancel:

    name: Cancel Previous Runs
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

  build:
    runs-on: ubuntu-22.04
    env:
      COMPILER: 'gcc-9'
      GITHUB_CI: true
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch the whole history
      - name: switch to gcc-9 on linux
        run: |
            sudo apt install g++-9 gcc-9
            sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 40 --slave /usr/bin/g++ g++ /usr/bin/g++-9 --slave /usr/bin/gcov gcov /usr/bin/gcov-9
      - name: Install
        run: ./.ci/install.sh
